name: Análise de Pull Requests em Múltiplos Repos (Python)

on:
  workflow_dispatch:
    inputs:
      num_pulls:
        description: 'Número de pull requests a serem coletados por repositório'
        required: false
        default: '10'
        type: string

jobs:
  coletar-e-analisar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Configurar Ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependências do Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Coletar os Pull Requests
        id: collect_pulls
        run: |
          # Gera os arquivos owner_repo_pulls.json
          python coletar_pull_requests.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOS_FILE: 'repositorios.json'
          NUM_PULLS: ${{ github.event.inputs.num_pulls }}

      - name: Extrair os Diffs dos Pull Requests
        run: |
          # Gera a pasta diffs/ com os arquivos .diff
          python extrair_diffs.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Simplificar e Agrupar Metadados (Formato Final)
        run: |
          # Gera o arquivo pr_info_simplificado.json no formato agrupado
          python simplificar_metadados.py

      - name: Criar Artefato com os Dados Coletados
        uses: actions/upload-artifact@v4
        with:
          name: pull-requests-data
          path: |
            # Arquivos brutos JSON, a pasta com todos os diffs e o JSON final simplificado
            *.json
            diffs/
            pr_info_simplificado.json  
          retention-days: 7